version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "emporiocase-rest-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-16x20c1cc88yb"
s3_prefix = "emporiocase-rest-api"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
